# cycle 2

In [1]:
import numpy as np

## 3 
### 8x8 matrix

In [3]:
x= np.zeros((8,8), dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4
### 1 D array each element present

In [4]:
arr1 = np.array([2,3,4,5,6,7])
print(arr1)
arr2 = np.array([4,3,7,9])
print(arr2)
print("comparison of two array is:")
print(np.in1d(arr1,arr2))

[2 3 4 5 6 7]
[4 3 7 9]
comparison of two array is:
[False  True  True False False  True]


## 5
### a. create two arrays
### b. common element
### c. union

In [5]:
a1 = np.array([0,1,2,4,5,6])
a2 = np.array([1,2,3,6,7,9])
print("intersection is: ",np.intersect1d(a1,a2))
print("union is: ",np.union1d(a1,a2))

intersection is:  [1 2 6]
union is:  [0 1 2 3 4 5 6 7 9]


## 6
### get unique element

In [7]:
a = np.array([1,1,2,2,3,4,4,5,6,7,7])
print(np.unique(a))

[1 2 3 4 5 6 7]


## 7
### convert numpy array to python list

In [8]:
arr = np.array([1,2,3,4])
print("array is: ",arr)
print(type(arr))
list = arr.tolist()
print("list is: ",list)
print(type(list))

array is:  [1 2 3 4]
<class 'numpy.ndarray'>
list is:  [1, 2, 3, 4]
<class 'list'>


In [49]:
y= np.zeros((8,8), dtype = int)
y[0::2,:2:1]=1
y[0::2,4:6:1]=1
y[1::2,2:4:1]=1
y[1::2,6:8:1]=1
print(y)

[[1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1]]


In [50]:
z=np.zeros((8,8),dtype=int)
z[0::2,4::1]=1
z[1::2,0:4:1]=1
print(z)

[[0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1]
 [1 1 1 1 0 0 0 0]]


## 8
### Write a numpy program to access array by column

In [56]:
array = np.array([[1,2,3],[4,8,11],[30,5,9]])
print(array)
print("accessing 3rd column: ")
print(array[:, 2])
print("accessing 2nd column: ")
print(array[:, 1])
print("accessing 1st column: ")
print(array[:, 0])

[[ 1  2  3]
 [ 4  8 11]
 [30  5  9]]
accessing 3rd column: 
[ 3 11  9]
accessing 2nd column: 
[2 8 5]
accessing 1st column: 
[ 1  4 30]


## 9 
## Write a numpy program to compute
   ### a)  multiplication of two given matrices.
   ### b)  addition of two matrices
